### ISSUE TITLE
Error: On Installation

### ISSUE THREAD

**Issue by isarwarfp** [jobmthomas/Docker-Bigdata#1]
I have followed simple steps:
1. Clone the repository
2. Run the command in docker plugin
docker-compose up --build
and got the error
```
 ---> 3ab5ae710c0a
Step 32/96 : RUN echo "export HADOOP_HOME=/hadoop/hadoop-2.7.7" >>~/.bash_profile
 ---> Running in e09d8c729e4b
Removing intermediate container e09d8c729e4b
 ---> 8f5b1cd73633
Step 33/96 : RUN echo "export PATH=$PATH:$HADOOP_HOME/bin" >>~/.bash_profile
 ---> Running in 036ea648c353
Removing intermediate container 036ea648c353
 ---> d16841ef652d
Step 34/96 : RUN $HADOOP_HOME/bin/hdfs namenode -format
 ---> Running in 1c1acfa3fe40
/hadoop/hadoop-2.7.7/etc/hadoop/hadoop-env.sh: line 16: $'\r': command not found
/hadoop/hadoop-2.7.7/etc/hadoop/hadoop-env.sh: line 18: $'\r': command not found
/hadoop/hadoop-2.7.7/etc/hadoop/hadoop-env.sh: line 23: $'\r': command not found
/hadoop/hadoop-2.7.7/etc/hadoop/hadoop-env.sh: line 26: $'\r': command not found
/hadoop/hadoop-2.7.7/etc/hadoop/hadoop-env.sh: line 32: $'\r': command not found
/hadoop/hadoop-2.7.7/etc/hadoop/hadoop-env.sh: line 34: $'\r': command not found
/hadoop/hadoop-2.7.7/etc/hadoop/hadoop-env.sh: line 36: syntax error near unexpected token `$'do\r''
'hadoop/hadoop-2.7.7/etc/hadoop/hadoop-env.sh: line 36: `for f in $HADOOP_HOME/contrib/capacity-scheduler/*.jar; do
/bin/java: No such file or directory304: /usr/lib/jvm/java-8-openjdk-amd64
ERROR: Service 'bigdata-cluster' failed to build: The command '/bin/sh -c $HADOOP_HOME/bin/hdfs namenode -format' returned a non-zero code: 127
```

**Comment by PabloChanivet** [comment]
Hi @imranbutt-java,
The problem is that hadoop-env.sh file contained in bigdata-cluster/config path is not in unix format. Just open it with notepad++ and convert it to unix format.
You will get more errors regarding the versions of some components, just update these versions for the latest available ones.

Regards

**Comment by jobmthomas** [comment]
@imranbutt-java Thanks for identifying the issue. I will fix it in this branch soon

**Comment by jobmthomas** [comment]
@PabloChanivet  I have made those changes. Updated the file formats and obsolete repositories. Happy that many people seeing this very useful.

**Comment by jobmthomas** [comment]
Issue resolved

**Comment by PabloChanivet** [comment]
> @PabloChanivet I have made those changes. Updated the file formats and obsolete repositories. Happy that many people seeing this very useful.

Thank you very much for making it available for us, it is really useful.
